version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/github_action
file_exists_behavior: OVERWRITE

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  ApplicationStart:
    - location: start.sh
      timeout: 60
      runas: ubuntu